MOMO_DASHBOARD/MOMO_DASHBOARD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('momo/', include("momo.urls")),
]

MOMO_DASHBOARD/momo/urls.py
from django.urls import path

from . import views

app_name = "momo"
urlpatterns = [
    path("", views.home, name="home"),
    path("airtime", views.airtime, name="airtime"),
    path("momotransfer", views.transfers_to_momo, name="transferstomomo"),
    path("paymenttocode", views.payment_to_code, name="paymenttocode"),
    path("cashpower", views.cashpower_payments, name="cashpower"),
    path("transactions", views.payments_to_third_parties, name="transactions"),
    path("withdrawals", views.withdrawals, name="withdrawals"),
    path("data", views.bundles_and_packs, name="data"),
    path("incomingmoney", views.moneyreceived, name="moneyrecieved"),
    path("bankdepo", views.bankdeposits, name="bankdepo"),
    path('api/transaction-data/', views.get_transaction_data, name='transaction_data'),
]

MOMO_DASHBOARD/momo/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AirtimePayments(models.Model):
    amount = models.IntegerField()
    service_provider = models.CharField(max_length=64)
    fee = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'airtime_payments'


class BankDeposits(models.Model):
    amount = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bank_deposits'


class BundlesAndPacks(models.Model):
    amount = models.IntegerField()
    service_provider = models.CharField(max_length=64)
    fee = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bundles_and_packs'


class CashPowerPayments(models.Model):
    amount = models.IntegerField()
    service_provider = models.CharField(max_length=64)
    fee = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'cash_power_payments'


class MoneyRecieved(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    amount = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'money_recieved'


class PaymentToCode(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    code = models.IntegerField()
    amount = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'payment_to_code'


class PaymentsToThirdParties(models.Model):
    amount = models.IntegerField()
    service_provider = models.CharField(max_length=64)
    fee = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'payments_to_third_parties'


class TransfersToMomo(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    tel = models.IntegerField()
    amount = models.IntegerField()
    fee = models.IntegerField(blank=True, null=True)
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'transfers_to_momo'


class Withdrawals(models.Model):
    agent = models.CharField(max_length=64)
    agent_tel = models.IntegerField()
    amount = models.IntegerField()
    fee = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'withdrawals'

MOMO_DASHBOARD/momo/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.db.models.functions import TruncMonth
from datetime import datetime, timedelta
from django.http import JsonResponse
from .models import (
    AirtimePayments,
    MoneyRecieved,
    TransfersToMomo,
    BankDeposits,
    PaymentToCode,
    CashPowerPayments,
    Withdrawals,
    PaymentsToThirdParties,
    BundlesAndPacks,
)
import json


# Create your views here.
def home(request):
    # retrieving transaction counts for each model
    transaction_counts = {
        "airtime": AirtimePayments.objects.count(),
        "bank_deposits": BankDeposits.objects.count(),
        "bundles_packs": BundlesAndPacks.objects.count(),
        "cash_power": CashPowerPayments.objects.count(),
        "money_received": MoneyRecieved.objects.count(),
        "payments_code": PaymentToCode.objects.count(),
        "third_party": PaymentsToThirdParties.objects.count(),
        "momo_transfers": TransfersToMomo.objects.count(),
        "withdrawals": Withdrawals.objects.count(),
    }

    # Calculating total number of transactions of all models
    total_transactions = sum(transaction_counts.values())

    # Avoiding ZeroDivisionError
    if total_transactions == 0:
        percentages = {key: 0 for key in transaction_counts}
    else:
        percentages = {key: (count / total_transactions) * 100 for key, count in transaction_counts.items()}

    # adding percentages to the template
    context = {
        "airtime_percentage": percentages["airtime"],
        "bank_deposits_percentage": percentages["bank_deposits"],
        "bundles_packs_percentage": percentages["bundles_packs"],
        "cash_power_percentage": percentages["cash_power"],
        "money_received_percentage": percentages["money_received"],
        "payments_code_percentage": percentages["payments_code"],
        "third_party_percentage": percentages["third_party"],
        "momo_transfers_percentage": percentages["momo_transfers"],
        "withdrawals_percentage": percentages["withdrawals"],
    }

    return render(request, "momo/index.html", context)


def airtime(request):
    return render(
        request, "momo/airtime.html", {"airtime": AirtimePayments.objects.all()}
    )


def transfers_to_momo(request):
    return render(
        request,
        "momo/momotransfer.html",
        {"momotransfers": TransfersToMomo.objects.all(),
         },
    )


def bankdeposits(request):
    return render(
        request, "momo/bankdepo.html", {"bankdepo": BankDeposits.objects.all()}
    )


def payment_to_code(request):
    return render(
        request,
        "momo/paymenttocode.html",
        {"paymenttocode": PaymentToCode.objects.all()},
    )


def cashpower_payments(request):
    return render(
        request, "momo/cashpower.html", {"cashpower": CashPowerPayments.objects.all()}
    )


def payments_to_third_parties(request):
    return render(
        request,
        "momo/transactions.html",
        {"transactions": PaymentsToThirdParties.objects.all()},
    )


def withdrawals(request):
    return render(
        request, "momo/withdrawals.html", {"withdrawals": Withdrawals.objects.all()}
    )


def bundles_and_packs(request):
    return render(request, "momo/data.html", {"data": BundlesAndPacks.objects.all()})


def moneyreceived(request):
    return render(
        request,
        "momo/incomingmoney.html",
        {"moneyrecieved": MoneyRecieved.objects.all()},
    )


def get_transaction_data(request):
    # Getting data for the last 12 months
    end_date = datetime.now()
    start_date = end_date - timedelta(days=365)

    # Total transaction volume by type
    transaction_volumes = {
        "Airtime": AirtimePayments.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Bank Deposits": BankDeposits.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Bundles": BundlesAndPacks.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Cash Power": CashPowerPayments.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Money Received": MoneyRecieved.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Code Payments": PaymentToCode.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Third Party": PaymentsToThirdParties.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "MOMO Transfers": TransfersToMomo.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
        "Withdrawals": Withdrawals.objects.filter(
            date__range=[start_date, end_date]
        ).aggregate(total=Sum("amount"))["total"]
        or 0,
    }

    # Monthly transaction totals
    monthly_data = {}
    for model in [
        AirtimePayments,
        BankDeposits,
        BundlesAndPacks,
        CashPowerPayments,
        MoneyRecieved,
        PaymentToCode,
        PaymentsToThirdParties,
        TransfersToMomo,
        Withdrawals,
    ]:
        monthly_totals = (
            model.objects.filter(date__range=[start_date, end_date])
            .annotate(month=TruncMonth("date"))
            .values("month")
            .annotate(total=Sum("amount"))
            .order_by("month")
        )

        for entry in monthly_totals:
            month_str = entry["month"].strftime("%Y-%m")
            if month_str not in monthly_data:
                monthly_data[month_str] = 0
            monthly_data[month_str] += entry["total"]

    # Service provider distribution
    provider_data = {}
    for model in [
        AirtimePayments,
        BundlesAndPacks,
        CashPowerPayments,
        PaymentsToThirdParties,
    ]:
        provider_totals = (
            model.objects.filter(date__range=[start_date, end_date])
            .values("service_provider")
            .annotate(total=Sum("amount"))
        )

        for entry in provider_totals:
            provider = entry["service_provider"]
            if provider not in provider_data:
                provider_data[provider] = 0
            provider_data[provider] += entry["total"]

    return JsonResponse(
        {
            "transaction_volumes": transaction_volumes,
            "monthly_data": monthly_data,
            "provider_data": provider_data,
        }
    )

MOMO_DASHBOARD/momo/templates/momo/Incomingmoney.html
{% extends "./layout.html" %}
{% block tablename %}
    <h1 style="text-align: center;">Money Recieved</h1>
{% endblock %}
{% block body %}
                <thead>
                    <tr>
                        <th onclick="sortTable(0)">Date <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(1)">First Name <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(2)">Last Name <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(3)">Amount <i class="fa-solid fa-sort"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in moneyrecieved %}
                    <tr>
                        <td>{{ item.date }}</td>
                        <td>{{ item.first_name }}</td>
                        <td>{{ item.last_name }}</td>
                        <td>{{ item.amount }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
{% endblock%}

MOMO_DASHBOARD/momo/templates/momo/Transactions.html
{% extends "./layout.html" %}
{% block tablename %}
    <h1 style="text-align: center;">General Transactions</h1>
{% endblock %}
{% block body %}
                <thead>
                    <tr>
                        <th onclick="sortTable(0)">Date <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(1)">Amount <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(2)">Fee <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(3)">Service provider <i class="fa-solid fa-sort"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in transactions %}
                    <tr>
                        <td>{{ item.date }}</td>
                        <td>{{ item.amount }}</td>
                        <td>{{ item.fee }}</td>
                        <td>{{ item.service_provider.title }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
{% endblock%}

MOMO_DASHBOARD/momo/templates/momo/airtime.html
{% extends "./layout.html" %}
<!-- this html will inherit template from layout.html -->
{% block tablename %}
    <h1 style="text-align: center;">Airtime</h1>
{% endblock %}
{% block body %}
                <thead>
                    <tr>
                        <th onclick="sortTable(0)">Date <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(1)">Amount <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(2)">Fee <i class="fa-solid fa-sort"></i></th>
                        <th onclick="sortTable(3)">Service provider <i class="fa-solid fa-sort"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in airtime %}
                        <tr>
                            <td>{{ item.date }}</td>
                            <td>{{ item.amount }}</td>
                            <td>{{ item.fee }}</td>
                            <td>{{ item.service_provider }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
{% endblock%}

MOMO_DASHBOARD/momo/templates/momo/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      Momo Dashboard
    </title>
    <link rel="icon" type="image/png" href="./images/M_Logo.jpg" />
    <link rel="stylesheet" href="{% static 'momo/css/swag.css' %}" />

    <!-- box icons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
  </head>

  <body>
    <!-- header design -->
    <header class="header">
      <a href="#" class="logo"
        >M-dashboard <span class="animate" style="--i: 1"></span
      ></a>
      <div class="bx bx-menu" id="menu-icon">
        <span class="animate" style="--i: 2"></span>
      </div>
      <nav class="navbar">
        <a href="#home" class="active">Home</a>
        <a href="#dashboard">Dashboard</a>
        <a href="#history">History</a>
        <a href="#percentage_charts">Overview</a>

        <span class="active-nav"></span>
        <span class="animate" style="--i: 2"></span>
      </nav>
    </header>
    <!-- home section design -->
    <section class="home show-animate" id="home">
      <div class="home-content">
        <h1>
          MTN <span> MoMo</span
          ><span class="animate" style="--i: 2"></span>
        </h1>
        <div class="text-animate">
          <h3>Dashboard</h3>
          <span class="animate" style="--i: 3"></span>
        </div>
        <p>
            Hi there! I’m MTN MoMo Dashboard, your trusted mobile money "extension" app that tracks your transactions
            that lets you  view, categorize, analyse and display your transactions in an attractive way directly from your phone's message.
            Whether it’s funds transferred, bills paid, airtime topups, or cashpower bills paid, I’ve got you categorized – anytime, anywhere.
            I’m here to make tracking simple and accessible,.
             It’s all about giving you the convenience to track your MoMo Money spendings with ease.
 <br />
          <span class="animate" style="--i: 4"></span>
        </p>



        <div class="home-sci">

        <a href="#history"><i class='bx bxs-credit-card-front'></i>

        <span class="animate" style="--i: 6"></span>
      </div>

      <div class="home-imgHover"></div>
      <span class="animate home-img" style="--i: 7"></span>
    </section>

    <!-- dashboard section design -->
    <section class="dashboard" id="dashboard">
      <h2 class="heading">
         <span>Dashboard</span><span class="animate scroll" style="--i: 1"></span>
      </h2>
      <!-- dashboard -->
      <section class="charts" id="charts">
        <h2 class="heading">
          Transaction <span>Analysis</span>
          <span class="animate scroll" style="--i: 1"></span>
        </h2>

        <div class="charts-row">
          <!-- Transaction Volume Chart -->
          <div class="charts-column">
            <h3 class="title">
              Transaction Volume<span class="animate scroll" style="--i: 2"></span>
            </h3>
            <div class="charts-box">
              <div class="charts-content">
                <canvas id="transactionVolumeChart"></canvas>
              </div>
              <span class="animate scroll" style="--i: 3"></span>
            </div>
          </div>

          <!-- Monthly Trends Chart -->
          <div class="charts-column">
            <h3 class="title">
              Monthly Trends<span class="animate scroll" style="--i: 5"></span>
            </h3>
            <div class="charts-box">
              <div class="charts-content">
                <canvas id="monthlyTrendsChart"></canvas>
              </div>
              <span class="animate scroll" style="--i: 6"></span>
            </div>
          </div>

          <!-- Service Provider Distribution -->
          <div class="charts-column">
            <h3 class="title">
              Service Providers<span class="animate scroll" style="--i: 7"></span>
            </h3>
            <div class="charts-box">
              <div class="charts-content">
                <canvas id="providerDistributionChart"></canvas>
              </div>
              <span class="animate scroll" style="--i: 8"></span>
            </div>
          </div>
        </div>
      </section>
      <div class="dashboard-img">
        <img src="./images/dashboard Davy.jpg" alt="" />
        <span class="circle-spin"></span>
        <span class="animate scroll" style="--i: 2"></span>
      </div>

      <div class="dashboard-content">
        <h3>
          <span
            class="animate scroll"
            style="--i: 4"
          ></span>
        </h3>
      </div>
    </section>

    <!-- history section design -->
    <section class="history" id="history">
      <h2 class="heading">
      Transaction <span>History</span
        ><span class="animate scroll" style="--i: 1"></span>
      </h2>

      <div class="history-row">
        <div class="history-column">
          <h3 class="title">
            <span class="animate scroll" style="--i: 2"></span>
          </h3>

          <div class="history-box">
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:moneyrecieved' %}">
                  <div class="year"><i class="bx bx-table"></i>Incoming Money</div>
                  <h3>Money Recieved</h3>
                  <p>
                    Records of money recieved
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:airtime' %}">
                  <div class="year"><i class="bx bx-table"></i>Payments</div>
                  <h3>Airtime</h3>
                  <p>
                    Records of amounts paid to buy Airtime
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:transferstomomo' %}">
                  <div class="year"><i class="bx bx-table"></i>Transfers</div>
                  <h3>MoMo </h3>
                  <p>
                    Record of transfers to Mobile numbers
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:paymenttocode' %}">
                  <div class="year"><i class="bx bx-table"></i>Payments</div>
                  <h3>Payments To Codes</h3>
                  <p>
                    Records of general payment to code holders
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:cashpower' %}">
                  <div class="year"><i class="bx bx-table"></i>Payments</div>
                  <h3>Cashpower</h3>
                  <p>
                    Records of cashpower bill payments
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:transactions' %}">
                  <div class="year"><i class="bx bx-table"></i>Transactions</div>
                  <h3>Transactions</h3>
                  <p>
                    Records of transactions initiated by third parties
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:withdrawals' %}">
                  <div class="year"><i class="bx bx-table"></i>Withdrawals</div>
                  <h3>Cash Withdraw</h3>
                  <p>
                    Records of withdraws
                  </p>
                </a>
              </div>
            </div>
            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:data' %}">
                  <div class="year"><i class="bx bx-table"></i>Payments</div>
                  <h3>Data Bundles</h3>
                  <p>
                    Records of Data Bundles purchased
                  </p>
                </a>
              </div>
            </div>

            <div class="history-content">
              <div class="content">
                <a href="{% url 'momo:bankdepo' %}">
                  <div class="year">
                    <i class="bx bx-table"></i>Deposits
                  </div>
                  <h3>Bank Deposits</h3>
                  <p>
                    Records of Transactions initiated by banks transfers money to the user's Momo Account
                  </p>
                </a>
              </div>
            </div>
            <span class="animate scroll" style="--i: 3"></span>
          </div>
        </div>
            <span class="animate scroll" style="--i: 6"></span>
          </div>
        </div>
      </div>
    </section>

    <!-- charts section design -->
    <section class="charts" id="percentage_charts">
      <h2 class="heading">
         Transactions you do<span> Most</span
        ><span class="animate scroll" style="--i: 1"></span>
      </h2>
      <div class="charts-row">
        <div class="charts-column">
          <h3 class="title">
            Percentage analysis<span class="animate scroll" style="--i: 2"></span>
          </h3>

          <div class="charts-box">
            <div class="charts-content">
              <div class="progress">
                <h3>Incoming Money <span>{{ money_received_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Payments to code holders <span>{{ payments_code_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Transfers to mobile numbers <span>{{ momo_transfers_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Bank deposits <span>{{ bank_deposits_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Airtime bill payments <span>{{ airtime_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Cash power bill payments <span>{{ cash_power_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>
            </div>
            <span class="animate scroll" style="--i: 3"></span>
          </div>
        </div>

        <div class="charts-column">
          <h3 class="title">
            <span>Other</span> Transactions<span
              class="animate scroll"
              style="--i: 5"
            ></span>
          </h3>

          <div class="charts-box">
            <div class="charts-content">
              <div class="progress">
                <h3>Transactions by third paties <span>{{ third_party_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Withdrawal from agents <span>{{ withdrawals_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Bank Transfers <span>{{ withdrawals_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

              <div class="progress">
                <h3>Internet and voice bundle purchase <span>{{ bundles_packs_percentage|floatformat:2 }}%</span></h3>
                <div class="bar"><span></span></div>
              </div>

            </div>
            <span class="animate scroll" style="--i: 6"></span>
          </div>
        </div>
      </div>
    </section>

    <!-- footer design -->
    <footer class="footer">
      <div class="footer-text">
        <p>
          Copyright &copy; 2025 by Group 23(Remy, Tony, Prince, Manzi) | All Rights Reserved.
        </p>
        <span class="animate scroll" style="--i: 1"></span>
      </div>

      <div class="footer-iconTop">
        <a href="#"><i class="bx bx-up-arrow-alt"></i></a>
        <span class="animate scroll" style="--i: 3"></span>
      </div>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>

    <script>
      const scriptURL =
        "https://script.google.com/macros/s/AKfycbxFRX9Oz3oD9OXD6HhUK7Phl4XEfFUsWPm88LieOn0yiSyb5VVnXHnSnElODNIfXDo0/exec";
      const form = document.forms["submit-to-google-sheet"];
      const msg = document.getElementById("msg");

      form.addEventListener("submit", (e) => {
        e.preventDefault();
        fetch(scriptURL, { method: "POST", body: new FormData(form) })
          .then((response) => {
            msg.innerHTML = "Message sent successfully";
            setTimeout(function () {
              msg.innerHTML = "";
            }, 4000);
            form.reset();
          })
          .catch((error) => console.error("Error!", error.message));
      });
    </script>
  </body>
</html>
wnvcx

MOMO_DASHBOARD/momo/templates/momo/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      Transactions
    </title>

    <link rel="icon" type="image/png" href="./images/M_Logo.jpg" />
    <link rel="stylesheet" href="{% static 'momo/css/tables.css' %}" />

    <!-- box icons -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
  </head>

  <body>
    <main>
      <div class="wrapper">
        {% block tablename %}
        {% endblock %}

        <ul>
          <li><a href="{% url 'momo:home' %}" style="all: unset, ">Go Home</a></li>
          <li><a href="http://127.0.0.1:8000/momo/#history" style="all: unset">Go Back</a></li>
        </ul>
        <div class="table-container">
          <div class="search-section">
            <input type="text" class="search-input" id="searchInput" placeholder="Search...">
          </div>
            <table id="dataTable">
                {% block body %}
                {% endblock %}
            </table>
        </div>
      </div>
    <script>
        document.getElementById('searchInput').addEventListener('keyup', function() {
            const searchTerm = this.value.toLowerCase();
            const table = document.getElementById('dataTable');
            const rows = table.getElementsByTagName('tr');

            for (let i = 1; i < rows.length; i++) {
                const row = rows[i];
                const cells = row.getElementsByTagName('td');
                let found = false;

                for (let j = 0; j < cells.length; j++) {
                    const cell = cells[j];
                    if (cell.textContent.toLowerCase().indexOf(searchTerm) > -1) {
                        found = true;
                        break;
                    }
                }

                row.style.display = found ? '' : 'none';
            }
        });

        function sortTable(n) {
            const table = document.getElementById('dataTable');
            let switching = true;
            let dir = 'asc';
            let switchcount = 0;

            while (switching) {
                switching = false;
                const rows = table.getElementsByTagName('tr');

                for (let i = 1; i < rows.length - 1; i++) {
                    let shouldSwitch = false;
                    const x = rows[i].getElementsByTagName('td')[n];
                    const y = rows[i + 1].getElementsByTagName('td')[n];

                    if (dir === 'asc') {
                        if (x.textContent.toLowerCase() > y.textContent.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else {
                        if (x.textContent.toLowerCase() < y.textContent.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }

                    if (shouldSwitch) {
                        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                        switching = true;
                        switchcount++;
                    }
                }

                if (switchcount === 0 && dir === 'asc') {
                    dir = 'desc';
                    switching = true;
                }
            }
        }
    </script>
  </body>